title: hello
/id:
  post:
    body:
     application/json:
       schema: <<schema>>#Dom parser parses it :-(
       example: <<example>> #wrong json
     application1/json: #wrong media type
      schema: <<schema>>
      example: <<example>>
/ddd{:
  #wrong braces

/hello:
  uriParameters:
    id: #unused url praremter
      type: string
