// Template: Base Controller (ApiControllerBase.t4) version 2.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Description;
using OrdersWebApiSample.OrdersXml.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace OrdersWebApiSample.OrdersXml
{
    [RoutePrefix("orders")]
    public partial class OrdersController : ApiController
    {


        /// <summary>
		/// Create a new purchase order
		/// </summary>
		/// <param name="purchaseordertype"></param>
        [HttpPost]
        [Route("")]
        public virtual IHttpActionResult PostBase(Models.PurchaseOrderType purchaseordertype)
        {
            // Do not modify this code
            return  ((IOrdersController)this).Post(purchaseordertype);
        }

        /// <summary>
		/// gets an order by id
		/// </summary>
		/// <param name="id"></param>
		/// <returns>PurchaseOrderType</returns>
        [ResponseType(typeof(PurchaseOrderType))]
        [HttpGet]
        [Route("{id}")]
        public virtual IHttpActionResult GetBase([FromUri] string id)
        {
            // Do not modify this code
            return  ((IOrdersController)this).Get(id);
        }

        /// <summary>
		/// updates an order
		/// </summary>
		/// <param name="purchaseordertype"></param>
		/// <param name="id"></param>
        [HttpPut]
        [Route("{id}")]
        public virtual IHttpActionResult PutBase(Models.PurchaseOrderType purchaseordertype,[FromUri] string id)
        {
            // Do not modify this code
            return  ((IOrdersController)this).Put(purchaseordertype,id);
        }

        /// <summary>
		/// ship one or more order items
		/// </summary>
		/// <param name="itemstype"></param>
		/// <param name="id"></param>
        [HttpPut]
        [Route("{id}/ship")]
        public virtual IHttpActionResult PutShipBase(Models.ItemsType itemstype,[FromUri] string id)
        {
            // Do not modify this code
            return  ((IOrdersController)this).PutShip(itemstype,id);
        }

        /// <summary>
		/// gets the not shipped items of an order
		/// </summary>
		/// <param name="id"></param>
		/// <returns>ItemsType</returns>
        [ResponseType(typeof(ItemsType))]
        [HttpGet]
        [Route("{id}/notshipped")]
        public virtual IHttpActionResult GetNotshippedBase([FromUri] string id)
        {
            // Do not modify this code
            return  ((IOrdersController)this).GetNotshipped(id);
        }

        /// <summary>
		/// gets the already shipped items of an order
		/// </summary>
		/// <param name="id"></param>
		/// <returns>ItemsType</returns>
        [ResponseType(typeof(ItemsType))]
        [HttpGet]
        [Route("{id}/shipped")]
        public virtual IHttpActionResult GetShippedBase([FromUri] string id)
        {
            // Do not modify this code
            return  ((IOrdersController)this).GetShipped(id);
        }
    }
}
