// Template: Base Controller (ApiControllerBase.t4) version 0.1

using System;
using System.Collections.Generic;
using System.Web.Http;
using System.Web.Http.Description;
using MoviesWebApi2Sample.Movies.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace MoviesWebApi2Sample.Movies
{
    [RoutePrefix("movies")]
    public partial class MoviesController : ApiController
    {


        /// <summary>
		/// gets all movies in the catalogue
		/// </summary>
		/// <returns>IList<MoviesGetOKResponseContent></returns>
        [ResponseType(typeof(IList<MoviesGetOKResponseContent>))]
        [HttpGet]
        [Route("")]
        public virtual IHttpActionResult GetBase()
        {
            // Do not modify this code
            return ((IMoviesController)this).Get();
        }

        /// <summary>
		/// adds a movie to the catalogue
		/// </summary>
		/// <param name="moviespostrequestcontent"></param>
		/// <param name="access_token">Used to send a valid OAuth 2 access token. Do not use together with the &quot;Authorization&quot; header </param>
        [HttpPost]
        [Route("")]
        public virtual IHttpActionResult PostBase(Models.MoviesPostRequestContent moviespostrequestcontent,[FromUri] string access_token = null)
        {
            // Do not modify this code
            return ((IMoviesController)this).Post(moviespostrequestcontent,access_token);
        }

        /// <summary>
		/// get the info of a movie
		/// </summary>
		/// <param name="id"></param>
		/// <returns>IdGetOKResponseContent</returns>
        [ResponseType(typeof(IdGetOKResponseContent))]
        [HttpGet]
        [Route("{id}")]
        public virtual IHttpActionResult GetByIdBase([FromUri] string id)
        {
            // Do not modify this code
            return ((IMoviesController)this).GetById(id);
        }

        /// <summary>
		/// update the info of a movie
		/// </summary>
		/// <param name="idputrequestcontent"></param>
		/// <param name="id"></param>
        [HttpPut]
        [Route("{id}")]
        public virtual IHttpActionResult PutBase(Models.IdPutRequestContent idputrequestcontent,[FromUri] string id)
        {
            // Do not modify this code
            return ((IMoviesController)this).Put(idputrequestcontent,id);
        }

        /// <summary>
		/// remove a movie from the catalogue
		/// </summary>
		/// <param name="id"></param>
        [HttpDelete]
        [Route("{id}")]
        public virtual IHttpActionResult DeleteBase([FromUri] string id)
        {
            // Do not modify this code
            return ((IMoviesController)this).Delete(id);
        }

        /// <summary>
		/// rent a movie
		/// </summary>
		/// <param name="json"></param>
		/// <param name="id"></param>
		/// <param name="access_token">Used to send a valid OAuth 2 access token. Do not use together with the &quot;Authorization&quot; header </param>
        [HttpPut]
        [Route("{id}/rent")]
        public virtual IHttpActionResult PutRentBase(string json,[FromUri] string id,[FromUri] string access_token = null)
        {
            // Do not modify this code
            return ((IMoviesController)this).PutRent(json,id,access_token);
        }

        /// <summary>
		/// return a movie
		/// </summary>
		/// <param name="json"></param>
		/// <param name="id"></param>
		/// <param name="access_token">Used to send a valid OAuth 2 access token. Do not use together with the &quot;Authorization&quot; header </param>
        [HttpPut]
        [Route("{id}/return")]
        public virtual IHttpActionResult PutReturnBase(string json,[FromUri] string id,[FromUri] string access_token = null)
        {
            // Do not modify this code
            return ((IMoviesController)this).PutReturn(json,id,access_token);
        }

        /// <summary>
		/// gets the current user movies wishlist
		/// </summary>
		/// <param name="access_token">Used to send a valid OAuth 2 access token. Do not use together with the &quot;Authorization&quot; header </param>
		/// <returns>IList<WishlistGetOKResponseContent></returns>
        [ResponseType(typeof(IList<WishlistGetOKResponseContent>))]
        [HttpGet]
        [Route("wishlist")]
        public virtual IHttpActionResult GetWishlistBase([FromUri] string access_token = null)
        {
            // Do not modify this code
            return ((IMoviesController)this).GetWishlist(access_token);
        }

        /// <summary>
		/// add a movie to the current user movies wishlist
		/// </summary>
		/// <param name="json"></param>
		/// <param name="id"></param>
		/// <param name="access_token">Used to send a valid OAuth 2 access token. Do not use together with the &quot;Authorization&quot; header </param>
        [HttpPost]
        [Route("wishlist/{id}")]
        public virtual IHttpActionResult PostByIdBase(string json,[FromUri] string id,[FromUri] string access_token = null)
        {
            // Do not modify this code
            return ((IMoviesController)this).PostById(json,id,access_token);
        }

        /// <summary>
		/// removes a movie from the current user movies wishlist
		/// </summary>
		/// <param name="id"></param>
		/// <param name="access_token">Used to send a valid OAuth 2 access token. Do not use together with the &quot;Authorization&quot; header </param>
        [HttpDelete]
        [Route("wishlist/{id}")]
        public virtual IHttpActionResult DeleteByIdBase([FromUri] string id,[FromUri] string access_token = null)
        {
            // Do not modify this code
            return ((IMoviesController)this).DeleteById(id,access_token);
        }

        /// <summary>
		/// gets the user rented movies
		/// </summary>
		/// <returns>IList<RentedGetOKResponseContent></returns>
        [ResponseType(typeof(IList<RentedGetOKResponseContent>))]
        [HttpGet]
        [Route("rented")]
        public virtual IHttpActionResult GetRentedBase()
        {
            // Do not modify this code
            return ((IMoviesController)this).GetRented();
        }

        /// <summary>
		/// get all movies that are not currently rented
		/// </summary>
		/// <returns>IList<AvailableGetOKResponseContent></returns>
        [ResponseType(typeof(IList<AvailableGetOKResponseContent>))]
        [HttpGet]
        [Route("available")]
        public virtual IHttpActionResult GetAvailableBase()
        {
            // Do not modify this code
            return ((IMoviesController)this).GetAvailable();
        }
    }
}
