
// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;

namespace MoviesWebApi2Sample.Movies.Models
{
    public partial class RentedGetOKResponseContent
    {
        
        public int Id { get; set; }
        public string Name { get; set; }
        public string Director { get; set; }
        public string Genre { get; set; }
        public string Cast { get; set; }
        public decimal Duration { get; set; }
        public string Storyline { get; set; }
        public string Language { get; set; }
        public bool Rented { get; set; }
    } // end class

} // end Models namespace