#%RAML 0.8
---
title: JC-Interface - File Services
version: 0.0.1
protocols: [HTTPS]
baseUri: https://jag.gov.bc.ca
mediaType: application/json
securedBy: [basic]

securitySchemes:
  - basic:
      type: Basic Authentication

schemas:
  - charge: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "sectionTxt" : {
            "type" : "string"
          },
          "sectionDscTxt" : {
            "type" : "string"
          }
        }
      }  

  - participant: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "fullNm" : {
            "type" : "string"
          },
          "charge" : {
            "type" : "array",
            "items" : { 
              "$ref" : "charge" 
            }
          }
        }
      }

  - fileDetail: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "mdocJustinNo" : {
            "type" : "string"
          },
          "physicalFileId" : {
            "type" : "string"
          },
          "fileHomeAgencyId" : {
            "type" : "string"
          },
          "fileNumberTxt" : {
            "type" : "string"
          },
          "mdocSeqNo" : {
            "type" : "string"
          },
          "ticketSeriesTxt" : {
            "type" : "string"
          },
          "mdocRefTypeCd" : {
            "type" : "string"
          },
          "courtLevelCd" : {
            "type" : "string",
            "enum" : [ "P", "S", "A" ]
          },
          "courtClassCd" : {
            "type" : "string",
            "enum" : [ "A", "Y", "T", "F", "C", "M", "L", "R", "B", "D", "E", "G", "H", "N", "O", "P", "S", "V" ]
          },
          "warrantYN" : {
            "type" : "string",
            "enum" : [ "Y", "N" ]
          },
          "inCustodyYN" : {
            "type" : "string",
            "enum" : [ "Y", "N" ]
          },
          "nextApprDt" : {
            "type" : "string"
          },
          "pcssCourtDivisionCd" : {
            "type" : "string",
            "enum" : [ "I", "R", "F" ]
          },
          "participant" : {
            "type" : "array",
            "items" : { 
              "$ref" : "participant" 
            }
          }
        }
      }

  - fileSearchResponse: |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type" : "object",
        "properties" : {
          "responseCd" : {
            "type" : "string"
          },
          "responseMessageTxt" : {
            "type" : "string"
          },
          "recCount" : {
            "type" : "string"
          },
          "fileDetail" : {
            "type" : "array",
            "items" : { 
              "$ref" : "fileDetail" 
            }
          }
        }
      }

/files:
  displayName: Court File Resources
  /criminal:
    get:
      responses:
        200:
          body:
            application/json:
              schema: fileSearchResponse
        404:
          body:
            application/json:
              example: |
                {"message": "No items matching the given criteria were found."}    