#%RAML 0.8
title: Api
baseUri: http://mocksvc.mulesoft.com/mocks/00dfd4fb-9343-4d5a-ab6f-75f35cb00456
mediaType: application/xml
schemas:
    - xml: !include files/ipo.xsd
/orders:
  displayName: Orders
  post:
    description: Create a new purchase order
    body:
      schema: PurchaseOrderType
  /{id}:
    get:
      responses:
        200:
          body:
            schema: PurchaseOrderType