using System;

namespace Raml.Common
{
    public class RamlPropertiesManager
    {
        public static string BuildContent(string targetNamespace, string ramlOriginalSource, bool? useAsyncMethods, string clientRootClassName)
        {
            var content = string.Format("// do not edit this file{0}source: {1}{0}namespace: {2}{0}",
                Environment.NewLine, ramlOriginalSource, targetNamespace);

            if (useAsyncMethods != null)
                content += string.Format("async: {0}{1}", useAsyncMethods.Value, Environment.NewLine);

            if (!string.IsNullOrWhiteSpace(clientRootClassName))
                content += string.Format("client: {0}{1}", clientRootClassName, Environment.NewLine);

            return content;
        }

    }
}