using System;

namespace Raml.Common
{
    public class RamlPropertiesManager
    {
        public static string BuildContent(string targetNamespace, string ramlOriginalSource)
        {
            var content = string.Format("// do not edit this file{0}source: {1}{0}namespace: {2}{0}",
                Environment.NewLine, ramlOriginalSource, targetNamespace);
            return content;
        }

    }
}