title: Refactoring Examples - Extract resource type
/hello:
  get:
    description: |
      Retrieve resource
    responses:
      200:
        description: |
          Succesfully retrieved resource
  put:
    description: |
      Update an existing resource
    body:
      application/json:
    responses:
      204:
        description: |
          Succesfully updated the resource
