title: Refactoring Examples - Move to new file
/hello:
  get:
    description: |
      Retrieve resource
    responses:
      200:
        description: |
          Succesfully retrieved resource
  put:
    description: |
      Update an existing resource
    body:
      application/json:
    responses:
      204:
        description: |
          Succesfully updated the resource
/hello2:
  get:
  /{id}:
   put:
/accounts:
   get:
