#%RAML 1.0 Library
title: My Library
types:
  - Url:
      type: string
      pattern:  |
        dd
  - Entity:
      type: object
      discriminator: kind
      properties:
        name: string
        id: number
        kind: string
        icon_url:
          type: Url[]
        createdAt: date
        modifiedAt: date
        createdBy: User
  - User:
      type: Entity
      properties:
        createdItems:
          type: Entity[]
