// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ChinookAspNet5Sample.ChinookV1.Models
{
    public partial class InvoiceLine
    {
        


        public int Id { get; set; }


        public Track Track { get; set; }


        public decimal UnitPrice { get; set; }


        public int Quantity { get; set; }
    } // end class

} // end Models namespace

