// Template: Models (ApiModel.t4) version 3.0

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System.ComponentModel.DataAnnotations;

namespace ChinookAspNet5Sample.ChinookV1.Models
{
    public partial class Person
    {
        


        public int Id { get; set; }


        public string Title { get; set; }


        public string BirthDate { get; set; }

        [Required]
        public string FirstName { get; set; }

        [Required]
        public string LastName { get; set; }


        public string Address { get; set; }


        public string City { get; set; }


        public string State { get; set; }


        public string Country { get; set; }


        public string PostalCode { get; set; }


        public string Phone { get; set; }


        public string Fax { get; set; }


        public string Email { get; set; }
    } // end class

} // end Models namespace

