// Template: Base Controller (ApiControllerBase.t4) version 3.0

using System;
using System.Collections.Generic;
using System.Threading.Tasks;
using Microsoft.AspNet.Mvc;
using ChinookAspNet5Sample.ChinookV1.Models;

// Do not modify this file. This code was generated by RAML Web Api 2 Scaffolder

namespace ChinookAspNet5Sample.ChinookV1
{
    [Route("tracks")]
    public partial class TracksController : Controller
    {


		/// <returns>IList&lt;Track&gt;</returns>
        [HttpGet]
        [Route("")]
        public virtual IActionResult GetBase()
        {
            // Do not modify this code
            return  ((ITracksController)this).Get();
        }

		/// <param name="content"></param>
        [HttpPost]
        [Route("")]
        public virtual IActionResult PostBase([FromBody] Models.Track content)
        {
            // Do not modify this code
            return  ((ITracksController)this).Post(content);
        }

		/// <param name="id"></param>
		/// <returns>Track</returns>
        [HttpGet]
        [Route("{id}")]
        public virtual IActionResult GetByIdBase(string id)
        {
            // Do not modify this code
            return  ((ITracksController)this).GetById(id);
        }

		/// <param name="content"></param>
		/// <param name="id"></param>
        [HttpPut]
        [Route("{id}")]
        public virtual IActionResult PutBase([FromBody] Models.Track content,string id)
        {
            // Do not modify this code
            return  ((ITracksController)this).Put(content,id);
        }

		/// <param name="id"></param>
        [HttpDelete]
        [Route("{id}")]
        public virtual IActionResult DeleteBase(string id)
        {
            // Do not modify this code
            return  ((ITracksController)this).Delete(id);
        }

		/// <param name="id"></param>
		/// <returns>IDictionary&lt;string,IList&lt;Track&gt;&gt;</returns>
        [HttpGet]
        [Route("byartist/{id}")]
        public virtual IActionResult GetABase(string id)
        {
            // Do not modify this code
            return  ((ITracksController)this).GetA(id);
        }
    }
}
