
// This code was generated by RAML Web Api 2 Scaffolder

namespace RAML.WebApiExplorer.Tests.Types
{
    public partial class Attributes
    {
        
        public string P162834id { get; set; }
    } // end class

} // end Objects namespace