
// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;

namespace RAML.WebApiExplorer.Tests.Types
{
    public partial class BoundingBox
    {
        
        public string Type { get; set; }
    } // end class

} // end Objects namespace