// Template: Models (ApiModel.t4) version 0.1

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace FstabExplorerTest.Fstab.Models
{
    public partial class Entry
    {
        
		[JsonProperty("storage")]
        public Storage Storage { get; set; }
		[JsonProperty("options")]
        public IList<string> Options { get; set; }
		[JsonProperty("readonly")]
        public bool Readonly { get; set; }
    } // end class

} // end Models namespace
