
// This code was generated by RAML Web Api 2 Scaffolder

namespace RAML.WebApiExplorer.Tests.Types
{
    public partial class ForksPostResponse
    {
        
        public int Id { get; set; }
        public Owner Owner { get; set; }
        public string Name { get; set; }
        public string Full_name { get; set; }
        public string Description { get; set; }
        public bool Private { get; set; }
        public bool Fork { get; set; }
        public string Url { get; set; }
        public string Html_url { get; set; }
        public string Clone_url { get; set; }
        public string Git_url { get; set; }
        public string Ssh_url { get; set; }
        public string Svn_url { get; set; }
        public string Mirror_url { get; set; }
        public string Homepage { get; set; }
        public string Language { get; set; }
        public int Forks { get; set; }
        public int Forks_count { get; set; }
        public int Watchers { get; set; }
        public int Watchers_count { get; set; }
        public int Size { get; set; }
        public string Master_branch { get; set; }
        public int Open_issues { get; set; }
        public int Open_issues_count { get; set; }
        /// <summary>
        /// ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ
        /// </summary>
        public string Pushed_at { get; set; }
        /// <summary>
        /// ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ
        /// </summary>
        public string Created_at { get; set; }
        /// <summary>
        /// ISO 8601 format: YYYY-MM-DDTHH:MM:SSZ
        /// </summary>
        public string Updated_at { get; set; }
    } // end class

} // end Objects namespace