
// This code was generated by RAML Web Api 2 Scaffolder

namespace RAML.WebApiExplorer.Tests.Types
{
    public partial class Owner
    {
        
        public string Login { get; set; }
        public int Id { get; set; }
        public string Avatar_url { get; set; }
        public string Gravatar_id { get; set; }
        public string Url { get; set; }
    } // end class

} // end Objects namespace