// Template: Models (ApiModel.t4) version 0.1

// This code was generated by RAML Web Api 2 Scaffolder

using System;
using System.Collections.Generic;
using Newtonsoft.Json;

namespace FstabExplorerTest.Fstab.Models
{
    [JsonObject("nfs")]
    public partial class Storagenfs  : Storage
    {
        
		[JsonProperty("remotePath")]
        public string RemotePath { get; set; }
		[JsonProperty("server")]
        public string Server { get; set; }
    } // end class

} // end Models namespace
